// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDArjZsX03S14zghN7bfIV2OTdFQjz4Uz4',
    appId: '1:369697723634:web:1efc983a13c28a5835ec6b',
    messagingSenderId: '369697723634',
    projectId: 'chat-app-oandb',
    authDomain: 'chat-app-oandb.firebaseapp.com',
    storageBucket: 'chat-app-oandb.appspot.com',
    measurementId: 'G-VJB49DLFN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANz4kQzC933XtObXJqsdeG5DoI6hjaQFU',
    appId: '1:369697723634:android:9d1828579dffd4e435ec6b',
    messagingSenderId: '369697723634',
    projectId: 'chat-app-oandb',
    storageBucket: 'chat-app-oandb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCukhLMw-W3YTyodQYeVA4ezBpey4zi86o',
    appId: '1:369697723634:ios:f78f721285ddd5a835ec6b',
    messagingSenderId: '369697723634',
    projectId: 'chat-app-oandb',
    storageBucket: 'chat-app-oandb.appspot.com',
    iosBundleId: 'com.oandb.chat.privateChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCukhLMw-W3YTyodQYeVA4ezBpey4zi86o',
    appId: '1:369697723634:ios:746f9ec1b4816f4335ec6b',
    messagingSenderId: '369697723634',
    projectId: 'chat-app-oandb',
    storageBucket: 'chat-app-oandb.appspot.com',
    iosBundleId: 'com.oandb.chat.privateChat.RunnerTests',
  );
}
